### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by gbelyea** [konnecteam/ts-sequelize#1]
Is there a known problem with install for ts-sequelize at the moment?

npm install --save  ts-sequelize
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for ts-sequelize

npm ERR! A complete log of this run can be found in:

**Comment by ggrimbert** [comment]
For now ts-sequelize is not on NPM.

If you want to try it you need to clone the repository and build the project

**Comment by gbelyea** [comment]
ahhh gotcha... a bit new to this.. are there steps to follow in the docs somewhere, or in terms of speed to get going am i best to stay with cu8-sequelize-oracle ... was hoping this would be a better option as far as working with oracle was concerned...  Thanks for the reply.. Cheers

**Comment by ggrimbert** [comment]
I you want to use ts-sequelize, you have to clone it, then in the folder : 
```
npm install
npm run build
```

then in the dependencies of your project : 
```JSON
"ts-sequelize": "git+https://github.com/konnecteam/ts-sequelize.git#1.0.1"
```

Finally 
```
# in ts-sequelize folder
npm link
# inyour project
npm link ts-sequelize
```

After that, all is good to go


We've planned to put the project on npm, maybe in one week or two.

**Comment by gbelyea** [comment]
Thanks for the steps.. i appreciate it, already running with cu8 but issues are cropping up so i'll see what this can do!!! Cheers!

**Comment by gbelyea** [comment]
Any idea what i would be missing here? Basically i have just removed references to cu8 and working through the errors, but not sure what i am missing. 

TypeError: Cannot read property 'noTimezone' of undefined
    at new OracleDialect (D:/dev/ts-sequelize/build/lib/dialects/oracle/oracle-dialect.js:26:65)
    at new Sequelize (D:/dev/ts-sequelize/build/lib/sequelize.js:181:24)
    at Object.<anonymous> (D:/dev/itacit-graphql/models/index.js:10:17)

**Comment by ggrimbert** [comment]
You're missing the dialectOptions parameter. It needs to be defined. If you don't have any options; just pass {}

```javascript
new TsSequelize(DatabaseConfig, User, Password, sequelizeConf || {});
```

If you're using Sequelize for the first time, you should take a look at the docs. They're not hosted but you can generate them by using 
```
npm run docs
```
It will generate the docs and create a folder "site" in the project; just open index.html

**Comment by ggrimbert** [comment]
We are now on npm with our version 1.0.1.
