### ISSUE TITLE
silent oracledb package installation?

### ISSUE THREAD

**Issue by markcellus** [konnecteam/ts-sequelize#3]
I came over from https://github.com/sequelize/sequelize/issues/9285#issuecomment-399909732. It's great to have typescript support with this package! :+1: 

However, I couldn't help but notice that, upon initial `npm install`ation of this package, it installs `oracledb` package, which was really surprising. Why attempt to install this if I have no use for `oracledb` package?

I see [here](https://github.com/konnecteam/ts-sequelize/blob/ad1ce63022e5282b4e5340ec1db60b80e89ea914/package.json#L81-L83) that its declared in the package.json as an optional dependency, but `optionalDependencies` are always usually installed automatically. Can this be moved from `optionalDependencies`? You can always state this optional package in the README.

**Comment by ggrimbert** [comment]
We've thought about placing it into the devdependencies, but unless using ```--production``` flag the devdependencies are installed. Or if you meet the requirements for nodeoracledb,the installation will crash.
So we've decided to place it there, so it tries to install, and if it fails, it doesn't block you installation.

**Comment by markcellus** [comment]
Yeah but why does it need to be a dependency or devDependency? As a consumer, I would never need the `oracledb` dependency at all.

**Comment by ggrimbert** [comment]
This is a dependency, even if you don't need it. The tedious and postgres packages are installed too; the only difference is that you don't see them as they don't need to be compilated.

We need dependencies to run tests. However, this is a devdependencies; so it's only installed if you run npm install on the project; if you import ts-sequelize, you don't have this.

**Comment by markcellus** [comment]
If its necessary for tests, I see why it would be in `devDependencies` then. But having it in `optionalDependencies` or `dependencies` forces it to be installed for the consumer, which probably shouldn't happen.

**Comment by ggrimbert** [comment]
Is has been moved to devdependencies, this will not be installed if ts-sequelize is a dependency of your project
